# Generated by Django 4.2.5 on 2023-10-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="image",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="images/customize"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="is_custom",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="name_on_cover",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
