# Generated by Django 4.2.5 on 2023-10-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0002_order_image_order_is_custom_order_name_on_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="placed",
            field=models.BooleanField(default=False),
        ),
    ]
