# Generated by Django 4.2.5 on 2023-10-24 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_wishlist"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("checkout", "0003_order_placed"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.products"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="payment_option",
            field=models.CharField(
                choices=[("COD", "COD"), ("ONLINE", "ONLINE")],
                default="ONLINE",
                max_length=50,
            ),
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
    ]
