# Generated by Django 4.2.5 on 2023-10-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0004_cartitem_order_payment_option_delete_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_id",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
