# Generated by Django 4.1.6 on 2023-12-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to="images/products/<django.db.models.fields.related.ForeignKey>/",
            ),
        ),
    ]
