# Generated by Django 4.1.6 on 2023-12-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_alter_products_description_alter_products_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/products/"),
        ),
    ]
