# Generated by Django 4.2.5 on 2023-11-09 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_phones"),
        ("customize", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customize",
            name="phone_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.phones",
            ),
        ),
    ]
